# Generated by Django 5.0.4 on 2024-07-18 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_todo_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='created',
        ),
    ]
